### Space Seperated data

In [1]:
"""
  Problem Statement:
    You are given a 9 space separated numbers. 
    Write a python code to convert it into a 3x3 NumPy array of integers.
  Input:
    6 9 2 3 5 8 1 5 4
  Output:
      [[6 9 2]
      [3 5 8]
      [1 5 4]]
"""
import numpy as np
lis= [6, 9, 2, 3, 5, 8 ,1, 5, 4]

x= np.array(lis).reshape(3,3)
print(x)
print(x.dtype)


[[6 9 2]
 [3 5 8]
 [1 5 4]]
int32
